app/routes/pizzas.py
# app/routes/pizzas.py
import os
from flask import Blueprint, render_template, request, redirect, url_for
from werkzeug.utils import secure_filename
from app import db
from app.models import Pizzas

UPLOAD_FOLDER = 'app/static/img'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'webp'}

pizzae_bp = Blueprint('pipshash', __name__)

@pizzae_bp.route('/')
def listar_pizza():
    pizzae = Pizzas.query.all()
    return render_template('pipshash/listar_pizza.html', pipshash=pizzae)

@pizzae_bp.route('/new', methods=['GET', 'POST'])
def add_pizza():
    if request.method == 'POST':
        nombre = request.form['nombre']
        masa = request.form['masa']
        queso = request.form['queso']
        
        # Verifica si se subió un archivo
        if 'imagen' not in request.files:
            return "No se ha seleccionado ningún archivo", 400

        file = request.files['imagen']

        # Si no se seleccionó un archivo, o el archivo está vacío
        if file.filename == '':
            return "No se ha seleccionado ningún archivo", 400

        # Validar tipo de archivo
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(UPLOAD_FOLDER, filename))  # Guarda la imagen en la carpeta

            # Guarda solo el nombre del archivo en la BD
            new_pizza = Pizzas(nombre=nombre, masa=masa, queso=queso, imagen=filename)
            db.session.add(new_pizza)
            db.session.commit()


        return redirect(url_for('pipshash.listar_pizza'))
    return render_template('pipshash/create_pizza.html')

@pizzae_bp.route('/update/<int:id>', methods=['GET', 'POST'])
def update_pizza(id):
    pizzas = Pizzas.query.get_or_404(id)

    if request.method == 'POST':
        pizzas.nombre = request.form['nombre']
        pizzas.masa = request.form['masa']
        pizzas.queso = request.form['queso']

        # Verifica si se subió una nueva imagen
        if 'imagen' in request.files:
            file = request.files['imagen']

            if file and file.filename != '' and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file.save(os.path.join(UPLOAD_FOLDER, filename))  # Guarda la nueva imagen
                
                # Borra la imagen anterior si existe
                if pizzas.imagen:
                    old_image_path = os.path.join(UPLOAD_FOLDER, pizzas.imagen)
                    if os.path.exists(old_image_path):
                        os.remove(old_image_path)

                # Asigna la nueva imagen al objeto de la pizza
                pizzas.imagen = filename

        db.session.commit()
        return redirect(url_for('pipshash.listar_pizza'))

    return render_template('pipshash/update_pizza.html', pizzas=pizzas)

@pizzae_bp.route('/delete/<int:id>', methods=['GET', 'POST'])
def delete_pizzas(id):
    pizzas = Pizzas.query.get(id)
    db.session.delete(pizzas)
    db.session.commit()
    return redirect(url_for('pipshash.listar_pizza'))

    # Función para validar extensiones de archivo
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

app/templates/pipshash/create_pizza.html
{% extends 'base.html' %}

{% block title %}Agregar pizza{% endblock %}

{% block content %}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <h1 class="title">Crear nueva pizza</h1>
        <form method="POST" enctype="multipart/form-data">
            <div class="field">
                <label class="label">Nombre</label>
                <div class="control">
                    <input class="input" type="text" name="nombre" required>
                </div>
            </div>

            <div class="field">
                <label class="label">Masa</label>
                <div class="control">
                    <input class="input" type="text" name="masa" required>
                </div>
            </div>
            <div class="field">
                <label class="label">Queso</label>
                <div class="control">
                    <input class="input" type="text" name="queso" required>
                </div>
            </div>
            <div class="field">
                <label class="label"">Imagen</label>
                <div class="control">
                    <input class="input" type="file" name="imagen" required>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success" type="submit">Crear Pizza</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/pipshash/listar_pizza.html
{% extends 'base.html' %}

{% block title %}Pizzas{% endblock %}

{% block content %}
<div class="container">
    <div class="mb-5">
        <a href="{{ url_for('pipshash.add_pizza') }}" class="button is-success">
            <i class="fa-solid fa-plus"></i> &nbsp; Agregar pizza
        </a>
    </div>

    <div class="columns is-multiline">
        {% for pizza in pipshash %}
        <div class="column is-one-third">
            <div class="card">
                <div class="card-content has-text-centered">
                    <p class="title is-4">{{ pizza.nombre }}</p>
                </div>

                <div class="card-image has-text-centered">
                    <figure class="image is-4by3" style="max-width: 200px; margin: 0 auto;">
                        <img src="{{ url_for('static', filename='img/' + pizza.imagen) }}" alt="Imagen de {{ pizza.nombre }}">
                    </figure>
                </div>

                <div class="card-content">
                    <p><strong>Masa:</strong> {{ pizza.masa }}</p>
                    <p><strong>Queso:</strong> {{ pizza.queso }}</p>
                </div>

                <div class="card-footer has-text-centered" style="display: flex; justify-content: space-around; padding: 1rem;">
                    <a href="{{ url_for('pipshash.update_pizza', id=pizza.id) }}" class="button is-small is-link is-outlined">
                        <i class="fa-solid fa-pen-to-square"></i> Editar
                    </a>
                    <a href="{{ url_for('pipshash.delete_pizzas', id=pizza.id) }}" class="button is-small is-danger is-outlined">
                        <i class="fa-solid fa-trash"></i> Eliminar
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/pipshash/update_pizza.html
{% extends 'base.html' %}

{% block title %}Editar pizza{% endblock %}

{% block content %}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <h1 class="title">Editar pizza</h1>
        <form method="POST" enctype="multipart/form-data">
            <div class="field">
                <label class="label">Nombre</label>
                <div class="control">
                    <input class="input" type="text" name="nombre" value="{{ pizzas.nombre }}" required>
                </div>
            </div>
        
            <div class="field">
                <label class="label">Masa</label>
                <div class="control">
                    <input class="input" type="text" name="masa" value="{{ pizzas.masa }}" required>
                </div>
            </div>
        
            <div class="field">
                <label class="label">Queso</label>
                <div class="control">
                    <input class="input" type="text" name="queso" value="{{ pizzas.queso }}" required>
                </div>
            </div>
        
            <div class="field">
                <label class="label">Imagen actual</label>
                <div class="control">
                    {% if pizzas.imagen %}
                        <img src="{{ url_for('static', filename='img/' + pizzas.imagen) }}" alt="Imagen de la pizza" width="150">
                    {% else %}
                        <p>No hay imagen</p>
                    {% endif %}
                </div>
            </div>
        
            <div class="field">
                <label class="label">Nueva Imagen (opcional)</label>
                <div class="control">
                    <input class="input" type="file" name="imagen">
                </div>
            </div>
        
            <div class="field">
                <div class="control">
                    <button class="button is-success" type="submit">Actualizar pizza</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}