app/models/pedidos.py
from app import db

# Modelo Pedidos
class Pedidos(db.Model):
    __tablename__ = 'pedidos'
    id = db.Column(db.Integer, primary_key=True)
    orden_id = db.Column(db.Integer, db.ForeignKey('orden.id'), nullable=False)
    repartidor_id = db.Column(db.Integer, db.ForeignKey('repartidores.id'), nullable=False)
    pedidos = db.relationship('Orden', backref='pedido', lazy=True)

app/routes/pedidos.py
# app/routes/pizzas.py
from flask import Blueprint, render_template, request, redirect, url_for
from app import db
from app.models import Pedidos, Orden, Repartidores, Pizzas

pedidos_bp = Blueprint('pedidos', __name__)

@pedidos_bp.route('/')
def listar_pedidos():
    pedidos = Pedidos.query.all()
    ordenes = Orden.query.all()
    repartidores = Repartidores.query.all()
    pizzas = Pizzas.query.all()
    return render_template('pedidos/listar_pedidos.html', pedidos=pedidos, ordenes=ordenes, repartidores=repartidores, pizzas=pizzas)

@pedidos_bp.route('/newpedido', methods=['GET', 'POST'])
def add_pedido():
    if request.method == 'POST':
        orden = request.form['orden']
        repartidor = request.form['repartidor']
        new_pedido = Pedidos(orden_id=orden, repartidor_id=repartidor)
        db.session.add(new_pedido)
        db.session.commit()
        return redirect(url_for('pedidos.listar_pedidos'))
    ordenes = Orden.query.all()
    repartidores = Repartidores.query.all()
    return render_template('pedidos/create_pedido.html', ordenes=ordenes, repartidores=repartidores)

# Actualizar repartidor
@pedidos_bp.route('/pedidos/update/<int:id>', methods=['GET', 'POST'])
def update_pedido(id):
    repartidores = Repartidores.query.all()
    pedido = Pedidos.query.get(id)
    if request.method == 'POST':
        pedido.orden_id = request.form['orden']
        pedido.repartidor_id = request.form['repartidor']
        db.session.commit()
        return redirect(url_for('pedidos.listar_pedidos'))
    ordenes = Orden.query.all()
    return render_template('pedidos/update_pedido.html', pedido=pedido, ordenes=ordenes, repartidores=repartidores)

@pedidos_bp.route('/delete/<int:id>', methods=['GET', 'POST'])
def delete_pedido(id):
    pedido = Pedidos.query.get(id)
    db.session.delete(pedido)
    db.session.commit()
    return redirect(url_for('pedidos.listar_pedidos'))

@pedidos_bp.route('/neworden', methods=['GET', 'POST'])
def add_orden():
    if request.method == 'POST':
        pizza = request.form['pizza']
        cantidad = request.form['cantidad']
        pizza_obj = Pizzas.query.get(int(pizza))
        new_orden = Orden(pizza=pizza_obj, cantidad=int(cantidad))
        print(pizza, cantidad)
        db.session.add(new_orden)
        db.session.commit()
        return redirect(url_for('pedidos.listar_pedidos'))
    pizzas = Pizzas.query.all()
    return render_template('pedidos/create_orden.html', pizzas=pizzas)

@pedidos_bp.route('/orden/update/<int:id>', methods=['GET', 'POST'])
def update_orden(id):
    orden = Orden.query.get(id)
    pizzas = Pizzas.query.all()
    if request.method == 'POST':
        orden.pizza_id = request.form['pizza']
        orden.cantidad = request.form['cantidad']
        db.session.commit()
        return redirect(url_for('pedidos.listar_pedidos'))
    return render_template('pedidos/update_orden.html', orden=orden, pizzas=pizzas)

@pedidos_bp.route('/orden/delete/<int:id>', methods=['GET', 'POST'])
def delete_orden(id):
    orden = Orden.query.get(id)
    db.session.delete(orden)
    db.session.commit()
    return redirect(url_for('pedidos.listar_pedidos'))

app/templates/pedidos/create_orden.html
{% extends 'base.html' %}
{% block title %} Crear Orden {% endblock %}

{% block content %}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <h1 class="title">Crear nueva orden</h1>
        <form method="POST">
            <div class="field">
                <label class="label">Pizza</label>
                <div class="control">
                    <select class="label" name="pizza" id="pizza">
                        {% for pizza in pizzas %}
                            <option value="{{pizza.id}}">{{pizza.nombre}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="field">
                <label class="label">Cantidad</label>
                <div class="control">
                    <input class="input" type="number" name="cantidad" required>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success" type="submit">Crear Orden</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/pedidos/create_pedido.html
{% extends 'base.html' %}
{% block title %} Crear Pedido {% endblock %}

{% block content %}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <h1 class="title">Crear nuevo pedido</h1>
        <form method="POST">
            <div class="field">
                <label class="label">Orden</label>
                <div class="control">
                    <select class="label" name="orden" id="orden">
                        {% for orden in ordenes %}
                            <option value="{{orden.id}}">{{orden.id}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="field">
                <label class="label">Repartidor</label>
                <div class="control">
                    <select name="repartidor" id="repartidor">
                        {% for repartidor in repartidores %}
                            <option value="{{repartidor.id}}">{{repartidor.nombre}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success" type="submit">Crear Pedido</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/pedidos/listar_pedidos.html
{% extends 'base.html' %}
{% block title %} Lista de Pedidos {% endblock %}
{% block content %}
<div class="columns">
    <div class="column is-10 is-offset-1">
        <div class="columns">
            <div class="column is-6">
                <h2 class="title is-4 has-text-centered">Pedidos</h2>
                <div class="has-text-centered mb-4">
                    <a href="{{url_for('pedidos.add_pedido')}}" class="button is-success">
                        <i class="fa-solid fa-plus"></i> &nbsp; Agregar Pedido
                    </a>
                </div>
                <table class="table is-fullwidth">
                    <thead>
                        <tr>
                            <th>ID Pedido</th>
                            <th>Pizzas</th>
                            <th>Repartidor</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for pedido in pedidos %}
                            <tr>
                                <td>{{pedido.id}}</td>
                                <td>
                                    {% for orden in ordenes %}
                                        {% if pedido.orden_id == orden.id %}
                                            {% for pizza in pizzas %}
                                                {% if orden.pizza_id == pizza.id %}
                                                    {{ pizza.nombre ~ " x " ~ orden.cantidad }}
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for repartidor in repartidores %}
                                        {% if pedido.repartidor_id == repartidor.id %}
                                            {{ repartidor.nombre }}
                                        {% endif %}
                                    {% endfor %}
                                </td>
                                <td>
                                    <a href="{{ url_for('pedidos.update_pedido', id=pedido.id) }}" class="button is-small is-link">
                                        <i class="fa-solid fa-pen-to-square"></i>
                                    </a>
                                    <a href="{{ url_for('pedidos.delete_pedido', id=pedido.id) }}" class="button is-small is-danger">
                                        <i class="fa-solid fa-trash"></i>
                                    </a>  
                                </td>
                            </tr>
                                                            
                        {% endfor %}

                    
                    </tbody>
                </table>
            </div>

            <div class="column is-6">
                <h2 class="title is-4 has-text-centered">Órdenes</h2>
                <div class="has-text-centered mb-4">
                    <a href="{{url_for('pedidos.add_orden')}}" class="button is-success">
                        <i class="fa-solid fa-plus"></i> &nbsp; Agregar Orden
                    </a>
                </div>
                <table class="table is-fullwidth">
                    <thead>
                        <tr>
                            <th>ID Orden</th>
                            <th>Pizza</th>
                            <th>Cantidad</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for orden in ordenes %}
                            <tr>
                                <td>{{orden.id}}</td>
                                <td>
                                    {% for pizza in pizzas %}
                                        {% if orden.pizza_id == pizza.id %}
                                            {{ pizza.nombre }}
                                        {% endif %}
                                    {% endfor %}
                                </td>
                                <td>{{orden.cantidad}}</td>
                                <td>
                                    <a href="{{url_for('pedidos.update_orden', id=orden.id)}}" class="button is-small is-link">
                                        <i class="fa-solid fa-pen-to-square"></i>
                                    </a>
                                    <a href="{{url_for('pedidos.delete_orden', id=orden.id)}}" class="button is-small is-danger">
                                        <i class="fa-solid fa-trash"></i>
                                    </a>  
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/pedidos/update_orden.html
{% extends 'base.html' %}
{% block title %} Editar Orden {% endblock %}
{% block content %}
<div class="container">
    <h2 class="title is-4 has-text-centered">Editar Orden</h2>
    <form method="POST" action="{{ url_for('pedidos.update_orden', id=orden.id) }}">
        <div class="field">
            <label class="label">Pizza</label>
            <div class="control">
                <div class="select is-fullwidth">
                    <select name="pizza">
                        {% for pizza in pizzas %}
                            <option value="{{ pizza.id }}" {% if pizza.id == orden.pizza_id %}selected{% endif %}>
                                {{ pizza.nombre }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div class="field">
            <label class="label">Cantidad</label>
            <div class="control">
                <input class="input" type="number" name="cantidad" value="{{ orden.cantidad }}" required>
            </div>
        </div>
        <div class="field is-grouped">
            <div class="control">
                <button class="button is-link" type="submit">Guardar</button>
            </div>
            <div class="control">
                <a class="button is-light" href="{{ url_for('pedidos.listar_pedidos') }}">Cancelar</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/templates/pedidos/update_pedido.html
{% extends 'base.html' %}

{% block title %}Editar Pedido{% endblock %}

{% block content %}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <h1 class="title">Editar pedido</h1>
        <form method="POST">
            <div class="field">
                <label class="label">Orden</label>
                <div class="control">
                    <select class="label" name="orden" id="orden">
                        {% for orden in ordenes %}
                            <option value="{{orden.id}}">{{orden.id}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="field">
                <label class="label">Repartidor</label>
                <div class="control">
                    <select name="repartidor" id="repartidor">
                        {% for repartidor in repartidores %}
                            <option value="{{repartidor.id}}">{{repartidor.nombre}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success" type="submit">Crear Pedido</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}