app/models/repartidores.py
from app import db

# Modelo Repartidores
class Repartidores(db.Model):
    __tablename__ = 'repartidores'
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(200), nullable=False)
    placa_moto = db.Column(db.String(200), nullable=False)
    capacidad = db.Column(db.Integer, nullable=False)
    imagen = db.Column(db.String(50), nullable=False)
    pedidos = db.relationship('Pedidos', backref='repartidor', lazy=True)

app/routes/repartidores.py
import os
from flask import Blueprint, render_template, request, redirect, url_for
from werkzeug.utils import secure_filename
from app import db
from app.models import Repartidores  # Cambio aquí

repartidores_bp = Blueprint('repartidores', __name__)

UPLOAD_FOLDER = 'app/static/img'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

# Ruta para ver todos los repartidores
@repartidores_bp.route('/')
def listar_repartidores():
    repartidores = Repartidores.query.all()
    return render_template('repartidores/listar_repartidores.html', repartidores=repartidores)

# Ruta para crear un nuevo repartidor
@repartidores_bp.route('/repartidores/new', methods=['GET', 'POST'])
def add_repartidor():
    if request.method == 'POST':
        nombre = request.form['nombre']
        placa_moto = request.form['placa_moto']
        capacidad = request.form['capacidad']

        # Verifica si se subió un archivo
        if 'imagen' not in request.files:
            return "No se ha seleccionado ningún archivo", 400

        file = request.files['imagen']

        # Si no se seleccionó un archivo, o el archivo está vacío
        if file.filename == '':
            return "No se ha seleccionado ningún archivo", 400

        # Validar tipo de archivo
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(UPLOAD_FOLDER, filename))  # Guarda la imagen en la carpeta

            # Guarda solo el nombre del archivo en la BD
            new_repa = Repartidores(nombre=nombre, placa_moto=placa_moto, capacidad=capacidad, imagen=filename)
            db.session.add(new_repa)
            db.session.commit()
        return redirect(url_for('repartidores.listar_repartidores'))

    return render_template('repartidores/create_repartidor.html')

# Actualizar repartidor
@repartidores_bp.route('/repartidores/update/<int:id>', methods=['GET', 'POST'])
def update_repartidor(id):
    repartidor = Repartidores.query.get(id)
    if request.method == 'POST':
        repartidor.nombre = request.form['nombre']
        repartidor.placa_moto = request.form['placa_moto']
        repartidor.capacidad = request.form['capacidad']
        
        db.session.commit()
        return redirect(url_for('repartidores.listar_repartidores'))
    
    return render_template('repartidores/update_repartidor.html', repartidor=repartidor)

# Eliminar repartidor
@repartidores_bp.route('/repartidores/delete/<int:id>')
def delete_repartidor(id):
    repartidor = Repartidores.query.get(id)
    if repartidor:
        db.session.delete(repartidor)
        db.session.commit()
    return redirect(url_for('repartidores.listar_repartidores'))

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

app/templates/repartidores/create_repartidor.html
{% extends 'base.html' %}
{% block title %} Agregar Repartidor {% endblock %}
{% block content %}
<div class="columns">
    <div class="column is-6 is-offset-3">
        <div class="card">
            <div class="card-content">
                <h2 class="title is-4 has-text-centered">Agregar Repartidor</h2>
                <form action="{{ url_for('repartidores.add_repartidor') }}" method="post" enctype="multipart/form-data">
                    <div class="field">
                        <label class="label">Nombre:</label>
                        <div class="control">
                            <input class="input" type="text" name="nombre" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Placa de la Moto:</label>
                        <div class="control">
                            <input class="input" type="text" name="placa_moto" required>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Capacidad de Entregas:</label>
                        <div class="control">
                            <input class="input" type="number" name="capacidad" required>
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Imagen</label>
                        <input class="input" type="file" name="imagen">
                    </div>

                    <div class="buttons">
                        <button class="button is-success" type="submit">Agregar</button>
                        <a class="button is-danger" href="{{ url_for('repartidores.listar_repartidores') }}">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/repartidores/listar_repartidores.html
{% extends 'base.html' %}
{% block title %}Lista de Repartidores{% endblock %}

{% block content %}
<div class="container">
    <a href="{{ url_for('repartidores.add_repartidor') }}" class="button is-success">
        <i class="fa-solid fa-plus"></i> &nbsp; Agregar Repartidor
    </a>
    <br><br>

    <div class="columns is-multiline">
        {% for repartidor in repartidores %}
        <div class="column is-4">
            <div class="card">
                <div class="card-content has-text-centered">
                    <p class="title is-4">{{ repartidor.nombre }}</p>
                </div>

                <div class="card-image has-text-centered">
                    <figure class="image is-4by3" style="max-width: 200px; margin: 0 auto;">
                        <img src="{{ url_for('static', filename='img/' + repartidor.imagen) }}" alt="Imagen de {{ repartidor.nombre }}">
                    </figure>
                </div>

                <div class="card-content">
                    <p><strong>Placa:</strong> {{ repartidor.placa_moto }}</p>
                    <p><strong>Capacidad:</strong> {{ repartidor.capacidad }}</p>
                </div>

                <div class="card-footer has-text-centered" style="display: flex; justify-content: space-around; padding: 1rem;">
                    <a href="{{ url_for('repartidores.update_repartidor', id=repartidor.id) }}" class="button is-small is-link is-outlined">
                        <i class="fa-solid fa-pen-to-square"></i> Editar
                    </a>
                    <a href="{{ url_for('repartidores.delete_repartidor', id=repartidor.id) }}" class="button is-small is-danger is-outlined">
                        <i class="fa-solid fa-trash"></i> Eliminar
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/repartidores/update_repartidor.html
{% extends 'base.html' %}
{% block title %} Actualizar Repartidor {% endblock %}
{% block content %}
<div class="columns">
    <div class="column is-6 is-offset-3">
        <div class="card">
            <div class="card-content">
                <h2 class="title is-4 has-text-centered">Actualizar Repartidor</h2>
                <form action="{{ url_for('repartidores.update_repartidor', id=repartidor.id) }}" method="post">

                    <div class="field">
                        <label class="label">Nombre:</label>
                        <div class="control">
                            <input class="input" type="text" name="nombre" value="{{ repartidor.nombre }}">
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Placa de la Moto:</label>
                        <div class="control">
                            <input class="input" type="text" name="placa_moto" value="{{ repartidor.placa_moto }}">
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Capacidad de Entregas:</label>
                        <div class="control">
                            <input class="input" type="number" name="capacidad" value="{{ repartidor.capacidad }}">
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Imagen actual</label>
                        <div class="control">
                            {% if repartidor.imagen %}
                                <img src="{{ url_for('static', filename='img/' + repartidor.imagen) }}" alt="Imagen del repartidor" width="150">
                            {% else %}
                                <p>No hay imagen</p>
                            {% endif %}
                        </div>
                    </div>
                
                    <div class="field">
                        <label class="label">Nueva Imagen (opcional)</label>
                        <div class="control">
                            <input class="input" type="file" name="imagen">
                        </div>
                    </div>

                    <div class="buttons">
                        <button class="button is-success" type="submit">Actualizar</button>
                        <a class="button is-danger" href="{{ url_for('repartidores.listar_repartidores') }}">Cancelar</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}